config/routes.rb
App::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 get 'allusers', to: 'users#index', as: 'allusers'
get 'user_path',to: 'user#show' , as: 'user_path'
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :users, only: [:update, :index, :show]

  root to: "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ApplicationRecord
	 def to_params
    { 'refresh_token' => refresh_token,
      'client_id'     => ENV['CLIENT_ID'],
      'client_secret' => ENV['CLIENT_SECRET'],
      'grant_type'    => 'refresh_token'}
  end

  def request_token_from_google
    url = URI("https://accounts.google.com/o/oauth2/token")
    Net::HTTP.post_form(url, self.to_params)
  end

  def refresh!
    data = JSON.parse(request_token_from_google.body)
    update_attributes(
      token: data['access_token'],
      expires_at: Time.now + data['expires_in'].to_i.seconds
    )
  end
  
  def self.access_token
    #convenience method to retrieve the latest token and refresh if necessary
    t = Token.last
    t.refresh! if t.expires_at < Time.now
    t.token
  end

end

app/models/user.rb
class User < ApplicationRecord
	  def self.from_omniauth(auth)
	  	byebug
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
     user.refresh_token = auth.credentials.refresh_token
     user.email = auth.info.email

      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    byebug
    end
  end


 def to_params
 	byebug
    { 'refresh_token' => refresh_token,
      'client_id'     => '1058339180581-et1k3u81ll6ji8q27bs3q777u1do8tdc.apps.googleusercontent.com',
      'client_secret' => 'vn-Aa97wDFInTxxz7cAgl6RD',
      'grant_type'    => 'refresh_token'}
end
  def refresh!
  	byebug
    data = JSON.parse(request_token_from_google.body)
    update_attributes(
      oauth_token: data['access_token'],
      oauth_expires_at: Time.now + data['expires_in'].to_i.seconds
    )
	end
	def request_token_from_google
	    url = URI("https://accounts.google.com/o/oauth2/token")
	    Net::HTTP.post_form(url, self.to_params)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
require 'gmail_xoauth'

class HomeController < ApplicationController
  def show
  	
  end
end

app/controllers/sessions_controller.rb
require 'gmail_xoauth'
require 'gmail'
require 'google/apis/gmail_v1'
#require 'googleauth'
require 'googleauth/stores/file_token_store'
require 'mail'
#require 'mail-xaouth'
  
require 'json'
require 'net/smtp'
require 'fileutils'


class SessionsController < ApplicationController
  def create
user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    session[:user_auth_token] = user.oauth_token
#      imap = Net::IMAP.new('imap.googlemail.com', 993, usessl = true, certs = nil, verify = false)
#     byebug

# 	imap.authenticate('XOAUTH2', 'aishwary.athlete@gmail.com', user.oauth_token)
# 	 xmessages_count = imap.status('INBOX', ['MESSAGES'])['MESSAGES']
# 	 #puts "Seeing #{messages_count} messages in INBOX"
# 	 #gmail = Gmail.new(:xoauth2, 'aishwary.athlete@gmail.com', ' user.oauth_token')
#    # gmail = Gmail.connect("aishwary.athlete@gmail.com","untroddenaish")
#      puts xmessages_count
#      #report = { bot: 1138, temp: 42, flux: 10 }

# # options = { :address              => "smtp.gmail.com",
# #             :port                 => 587,
# #             :user_name            => 'aishwary.athlete@gmail.com',
# #             :password             => 'untroddenaish',
# #             :authentication       => 'plain',
# #             :enable_starttls_auto => true  }

# # Mail.defaults do
# #   delivery_method :smtp, options
# # end
# # Mail.deliver do
# #        to 'aishwary.athlete@gmail.com '
# #      from 'aishwary.athlete@gmail.com '
# #   subject 'Test'
# #      body 'Hurray!!! Test email!'
# # end
# smtp = Net::SMTP.new('smtp.gmail.com', 587)
# smtp.enable_starttls_auto

# smtp.start('gmail.com', 'aishwary.athlete@gmail.com', user.oauth_token, :xoauth2)
# # Mail.defaults do
# #    delivery_method :smtp
# #  end
# #  byebug
# # Mail.deliver do
# #   to 'aishwary.athlete@gmail.com'
# #   from 'aishwary.athlete@gmail.com'
# #   subject 'Token'
# #   body 'Hurray!!! Test email!'
# # end
# smtp.finish

#   smmtp = Net::SMTP.new('smtp.gmail.com', 587)
#   smmtp.enable_starttls_auto
#   smmtp.start('gmail.com', 'aishwary.athlete@gmail.com', user.oauth_token, :xoauth2)
#   message = "\ 
#   From: Your Name <your@mail.address>\
#   To: Destination Address <someone@example.com>\
#   Subject: test message\
#   Date: Sat, 23 Jun 2001 16:26:43 +0900\
#   Message-Id: <unique.message.id.string@example.com>\
#   \
#   This is a test message."

#   smmtp.send_message message, 'aishwary.athlete@gmail.com', 'aishwary.athlete@gmail.com'
#   smmtp.finish
#     #puts  gmail.inbox.count
    redirect_to root_path
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

#user.oauth_token








end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_specific, only: [:show, :update]

  def index
  	 @users = User.all
  end

  def show
  end

 
  def update		
    byebug
    t = @user.oauth_token  
    @user.refresh! if @user.oauth_expires_at < Time.now
    #t.oauth_token
    byebug
 		smmtp = Net::SMTP.new('smtp.gmail.com', 587)
	  smmtp.enable_starttls_auto
	  byebug
	  smmtp.start('gmail.com', @user.email, @user.oauth_token, :xoauth2)
	  message = <<MESSAGE_END
From: Private Person <me@fromdomain.com>
To: #{params[:user][:email]}
MIME-Version: 1.0
Content-type: text/html
Subject: #{params[:user][:email]}
<%byebug%>
This is an e-mail message to be sent in HTML format

<b>This is HTML message.</b>
<h1>This is headline.</h1>
MESSAGE_END

	  byebug
	  smmtp.send_message message,@user.email,params[:user][:to]
	  byebug
	  smmtp.finish

	  redirect_to users_url
  end

  private

  def user_specific
  	@user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Auth Example App</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <%= link_to "allusers", allusers_path, id: "allusers" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Listing All users</h1>
 
<table>
  <tr>
    <th>Name</th>
     <th>Email</th>
    <th> oauth_token</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.refresh_token %></td>
       <td><%= user.oauth_token %></td>
        <td><%= link_to 'SEND MAIL',user_path(user) %></td>
       
     
    </tr>
  <% end %>
</table>

"

app/views/users/show.html.erb
<h1>Show#inside</h1>
<p>Find me in app/views/show/inside.html.erb</p>
    render html: "mail sent"
<%= form_for :user, method: :patch do |f| %>

			</br>
      </br>
      </br>
      
      <%= f.label :To %>
      <%= email_field_tag "user[to]" %>

      </br>
      </br>
      </br>

      <%= f.label :subject %>
      <%= text_field_tag "user[subject]" %>

      </br>
      </br>
      </br>
      
      <%= f.label :body%>
      <%= text_field_tag "user[body]" %>

      </br>
      </br>
      </br>

        <%= f.submit "Send"%>
    <% end %>